version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "friday"
- package-ecosystem: "docker"
  directory: "/examples/rails-7-barebones/"
  schedule:
    interval: "weekly"
    day: "friday"
