version: "3"
services:
  otel:
    image: quay.io/signalfx/splunk-otel-collector:0.59.1
    command: ["--config=/conf/otel-collector-config.yaml"]
    privileged: true
    ports:
      - 4318:4318
      - 8378:8378
    volumes:
      - ./conf/otel-collector-config.yaml:/conf/otel-collector-config.yaml
