# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

gem "puma"
gem "rails", "~> 7.0.3"

gem "opentelemetry-instrumentation-rails", "~> 0.21.0"
gem "splunk-otel", path: "../../"
