# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# rails app
gem "puma"
gem "rails", "~> 7.0.3"

# instrumentation
gem "opentelemetry-instrumentation-rails", "~> 0.21.0"
gem "splunk-otel", path: ENV.fetch("SPLUNK_OTEL_LOCATION", "../../")

# tests
gem "test-unit", "~> 3.0"
