version: '3.7'

services:
  postgres:
    image: cimg/postgres:14.2
    environment:
      - POSTGRES_USER=test
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
