version: '3.7'

services:
  postgres:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
