# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in http_roundtrip.gemspec
gemspec

gem "rake", "~> 13.0"

gem "test-unit", "~> 3.0"

gem "rubocop", "~> 1.7"

gem "httpclient"
gem "opentelemetry-instrumentation-http_client"
gem "splunk-otel", path: "../../"
